name: Bump version & publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Select package'
        required: true
        type: choice
        options:
          - 'channels'
          - 'use-channels'
      version:
        description: 'Semver type of new version'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install npm packages
        run: |
          cd packages/${{ github.event.inputs.package }}
          npm ci
      - name: bump version
        run: |
          echo "1. cd packages/${{ github.event.inputs.package }}"
