name: Bump version & publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Select package'
        required: true
        type: choice
        options:
          - 'channels'
          - 'use-channels'
      version:
        description: 'Semver type of new version'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install npm packages
        run: npm ci
      - name: Run tests
        run: |
          cd packages/${{ github.event.inputs.package }}
          npm run test
      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: bump version
        run: |
          echo "1. cd packages/${{ github.event.inputs.package }}" 
          cd packages/${{ github.event.inputs.package }}
          
          echo "2. npm version ${{ github.event.inputs.version }}" 
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          
          echo "3. git add"
          git add .
          
          echo "4. git commit ${{ github.event.inputs.package }} v$(npm pkg get version | tr -d '"')"
          git commit -m "${{ github.event.inputs.package }} v$(npm pkg get version | tr -d '"')"
          
          echo "5. git tag $(npm pkg get name | tr -d '"')@$(npm pkg get version | tr -d '"')"
          git tag $(npm pkg get name | tr -d '"')@$(npm pkg get version | tr -d '"')
      - name: publish
        run: |
          cd packages/${{ github.event.inputs.package }}
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push latest version
        run: git push origin main --follow-tags
